### PR TITLE
Update JSON schema to 2020-12

### PR DESCRIPTION
**Pull request by rhiaro**
# Overview

- What does this pull request do?

Updates the base metaschema to JSON Schema 2020-12 (from draft-04) and corresponding fixtures and docs. Only updates to replicate existing functionality with the new JSON Schema version - does not use new features or improvements.

Also updates some testing dependencies and updates the tests accordingly.

Changes:

* `id` to `$id`
* `definitions` to `$defs`
* semantics of `exclusiveMinimum` and `exclusiveMaximum`
* `enum`s with one value are now `const`
* updated `meta-schema.json`

(Closes/Relates to) issue: #469

### Tasks remaining

* [x] Update bodsVersion numbers in examples and tests data
* [x] Update min/maxs in examples data
* [x] Work out why there's a test failing on github - it passes for me locally.

## Translations

- [x] New or edited strings appearing as a result of this PR will be picked up for translation
  - The descriptions for `Interest / share / {minimum,maximum,exclusiveMinimum,exclusiveMaximum}` have changed
- [ ] I've notified the translation coordinator of any new strings that will need
      translating. See: https://openownership.github.io/bods-dev-handbook/translations.html

## Documentation & Release

- [x] I've thought about how and when this needs to be released. See:
      https://openownership.github.io/bods-dev-handbook/standard_releases.html      
- [x] I've updated the changelog, if necessary.
- [x] I've updated [reference.rst](https://standard.openownership.org/en/latest/schema/reference.html) to reflect any changes to schema structure or naming.
- [x] I've added or edited any other related documentation. See: https://github.com/openownership/bods-dev-handbook/blob/master/style_guide.md
  - See also: [PR to BODS dev handbook](https://github.com/openownership/bods-dev-handbook/pull/52)

### CODE REVIEW

**Comment by rhiaro** [comment]
@kd-ods Please could you check you agree with the changes in https://github.com/openownership/data-standard/pull/485/commits/dae15d35d35ece4fb29f46f0d0e8d3df14682b42? 

Note that I have not made the same changes to any instances of `maximum` where there was also an `exact` value. This is a different meaning from in 0.3 (where `maximum` meant `exclusiveMaximum` by default) but I suspect in the cases with an `exact` value that was actually incorrect, and it should have been an inclusive maximum. Can you confirm that's also correct?

**Review by kd-ods — COMMENTED** [review]
Right - I've eyeballed it all and suggested a couple of edits. I'm not the best person to review the tests and requirements though. I haven't thoroughly reviewed the metaschema, either: if you think I ought to be able to review it (for the sake of improving my schema development skills!) then let's go through it together next week?

**Comment by radix0000** [comment]
Have a couple of questions, but they aren't major issues and wouldn't block merging:

* data-standard/tests/test_json.py: lines 18-22 - might it be better to use pytest fixtures for schemas and metaschema rather than global variables (but seems like is a more general issue in code, so even if good idea may not be worth it)?
* data-standard/tests/test_json.py: line 23 - does this commented out code need to be here for some informational reason?
* examples/: replacement of maximum with exclusiveMaximum etc., get the impression that in previous versions where exclusiveMaximum was a boolean, it defaults to false (though couldn't find a reliable reference), so is this subtly changing the example and is that what is wanted?

**Comment by rhiaro** [comment]
Thanks @radix0000 

>    data-standard/tests/test_json.py: lines 18-22 - might it be better to use pytest fixtures for schemas and metaschema rather than global variables (but seems like is a more general issue in code, so even if good idea may not be worth it)?

+1 I've opened https://github.com/openownership/data-standard/issues/493 to capture this so we can work out how much work it is (probably not much?) and queue it for future improvement

>    data-standard/tests/test_json.py: line 23 - does this commented out code need to be here for some informational reason?

Removed

>   examples/: replacement of maximum with exclusiveMaximum etc., get the impression that in previous versions where exclusiveMaximum was a boolean, it defaults to false (though couldn't find a reliable reference), so is this subtly changing the example and is that what is wanted?

That's correct, the examples were technically wrong before, see https://github.com/openownership/data-standard/pull/485#issuecomment-1659640722

**Review by kd-ods — APPROVED** [review]
@rhiaro - this looks good, including your responses to @radix0000 review. I'll approve it but feel free to hold out for a dev's eye view from @radix0000.

**Pull request merged**
