### PR TITLE
Example drt main

### LINKED ISSUE #738: [BUG] - Example files need to be corrected on main and 0.4 release
**Summary of the bug or issue**

We effectively hand-rolled the example data for the 0.4 release. Unsurprisingly, the use of the example files for testing the updates to the Data Review Tool and the Visualiser uncovered various issues with the data. 

**Suggested resolution**

We should correct the example files. Once the tools are released we can do final tests on the corrected example files, merge into main, and then replicate on the release branch.

### PR DESCRIPTION
**Pull request by kathryn-ods**
# Overview

**What does this pull request do?**
Makes minor fixes to the examples files, identified by the DRT

**How can a reviewer test or examine your changes?**
Run a few through the DRT to check they're fine 

**Who is best placed to review it?**

Closes #738 

## Translations

- [ ] New or edited strings appearing as a result of this PR will be picked up for translation
- [ ] I've notified the translation coordinator of any new strings that will need
      translating. [See the Handbook](https://openownership.github.io/bods-dev-handbook/translations.html)

## Documentation & Release

- [ ] I've checked that the documentation builds without failing. [See the Handbook](https://github.com/openownership/data-standard#building-the-documentation-locally)
- [ ] I've thought about how and when this needs to be released. [See the Handbook](https://openownership.github.io/bods-dev-handbook/standard_releases.html)      
- [ ] I've updated the changelog, if necessary. [See the Handbook](https://openownership.github.io/bods-dev-handbook/standard_releases.html#changelog)
- [ ] I've updated [reference.rst](https://standard.openownership.org/en/latest/schema/reference.html) to reflect any changes to schema structure or naming.
- [ ] I've added or edited any other related documentation. [See the Handbook](https://github.com/openownership/bods-dev-handbook/blob/master/style_guide.md)

### CODE REVIEW

**Comment by kathryn-ods** [comment]
@kd-ods in addition to the fixes here all examples had the error 

> beneficialOwnershipOrControl expected to be 'true' in at least one Relationship statement with a person as an interested party. If this dataset contains beneficial owners, check that beneficialOwnershipOrControl is correctly used.	

Do we need to fix this?

**Comment by kathryn-ods** [comment]
I'm not sure why the docs linkcheck keeps breaking - I haven't made any docs changes so it shouldn't be. I think there's some sort of issue with the way it interacts with the ISO site.

**Comment by kd-ods** [comment]
> @kd-ods in addition to the fixes here all examples had the error
> 
> > beneficialOwnershipOrControl expected to be 'true' in at least one Relationship statement with a person as an interested party. If this dataset contains beneficial owners, check that beneficialOwnershipOrControl is correctly used.
> 
> Do we need to fix this?

I don't think we need to change the example files.

(It's a bit of an anomalous type of error message... since it's not an error, as such. It's a prompt for users of the tool to check that they are correctly using that field IF their dataset contains beneficial owners. There are definitely improvements to the user interface of the Data Review Tool which could make that clearer.)

**Comment by kd-ods** [comment]
The commit above fixes an issue [spotted here](https://github.com/openownership/visualisation-tool/issues/176#issuecomment-2505828115).

**Comment by kathryn-ods** [comment]
@kd-ods I think this still needs merging in? The link check is breaking for some reason other than the docs itself

**Comment by kd-ods** [comment]
It looks like the particular link that is failing the check is https://www.iso20022.org/market-identifier-codes - it's apparently timing out. However the link does not seem to be broken if checked by hand. 

I suspect that bots checking links are not welcomed in iso-land.

Do you think we should wait until the data review tool is released, do a final run of the data through it, before merging @kathryn-ods ?

**Comment by kathryn-ods** [comment]
> It looks like the particular link that is failing the check is https://www.iso20022.org/market-identifier-codes - it's apparently timing out. However the link does not seem to be broken if checked by hand.

I asked @rhiaro to look at this and they said

> looks like there's something wrong with the ssl cert handshake and it times out. Not sure how to fix it off the top of my head. I think it's an issue with openssl on ubuntu .. I haven't looked into exactly what is running the tests on github actions, but there's probably a version upgrade somewhere in there that would resolve it


> Do you think we should wait until the data review tool is released, do a final run of the data through it, before merging

I don't have strong feelings either way - what do you think?

**Review by kd-ods — CHANGES_REQUESTED** [review]
A couple of the files have discrepancies in the statementDates which need to be fixed.

**Review by kd-ods — APPROVED** [review]

**Pull request merged**
