### PR TITLE
changing subheadings in reference page to include spaces

### PR DESCRIPTION
**Pull request by kathryn-ods**
# Overview

- What does this pull request do? Adds spaces to the subheadings in the reference page
- How can a reviewer test or examine your changes? building the docs locally and checking the page?
- Who is best placed to review it? Kadie

(Closes/Relates to) issue: #

## Translations

- [ ] New or edited strings appearing as a result of this PR will be picked up for translation
- [ ] I've notified the translation coordinator of any new strings that will need
      translating. See: https://openownership.github.io/bods-dev-handbook/translations.html

## Documentation & Release

- [ ] I've thought about how and when this needs to be released. See:
      https://openownership.github.io/bods-dev-handbook/standard_releases.html      
- [ ] I've updated the changelog, if necessary.
- [ ] I've updated [reference.rst](https://standard.openownership.org/en/latest/schema/reference.html) to reflect any changes to schema structure or naming.
- [ ] I've added or edited any other related documentation. See: https://github.com/openownership/bods-dev-handbook/blob/master/style_guide.md

### CODE REVIEW

**Comment by kathryn-ods** [comment]
Kadie - I just changed the subheadings in the reference page as a small task to practice editing the docs and bring this page in line with the style guide conventions we discussed yesterday. Not sure if I need to do anything re: translations?

**Review by kd-ods — CHANGES_REQUESTED** [review]
The links from within tables will need to be updated to take account of the new headings. It's to do with how the HTML elements are generated from the RST and how the sphinx directives work. So, for example, if you try to follow the AddressType link from the first table on the page, it doesn't work.

In this directive:

```
.. jsonschema:: ../_build_schema/components.json
   :pointer: /$defs/Address
   :externallinks: {"type":{"url":"#addresstype","text":"AddressType"}}
   :allowexternalrefs:
```
the 'externallinks' bit needs to change to:

```
:externallinks: {"type":{"url":"#address-type","text":"Address Type"}}
```
(This is one of the gnarly things we need to make sure we document in the Handbook!)

**Comment by kathryn-ods** [comment]
Thanks @kd-ods I will get those fixed

**Comment by kathryn-ods** [comment]
@kd-ods I have fixed the broken links in the reference page and checked/fixed relevant links on the other pages

**Comment by kathryn-ods** [comment]
also edited the components file as there was a broken link under annotations 

"An RFC6901 JSON Pointer (https://tools.ietf.org/html/rfc6901)"

**Review by kd-ods — APPROVED** [review]
Great - I've built this and checked the links. It's ready to merge. 

We can do that on a call together if helpful.

**Pull request merged**
